name: ape_nft
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.3
  gap: ^2.0.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^2.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/apes/
    - assets/background/
